[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    ; TODO: tambahkan dependency, contoh:
    ; dfrobot/DFRobotDFPlayerMini @ 1.0.6
    ; bblanchon/ArduinoJson @ 7.0.0
